### ISSUE TITLE
Solucionas errores?

### ISSUE THREAD

**Issue by SherlockEspitia** [FaztWeb/express-first-server#1]
Me tira un error con un modulo faltante para iniciar el servidor, luego de ejecutar  start

> primerserver@1.0.0 start C:\Users\agame\Documents\Ejemplos Programacion\Node.Js Fazt\PrimerServer
> node app.js

module.js:491
    throw err;
    ^

Error: Cannot find module 'C:\Users\agame\Documents\Ejemplos Programacion\Node.Js Fazt\PrimerServer\app.js'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! primerserver@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the primerserver@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\agame\AppData\Roaming\npm-cache\_logs\2017-12-28T05_23_58_929Z-debug.log

**Comment by descobardos** [comment]
Debes ejecutar      npm run dev
para utilizar el script del package.jason
`    "start": "node app.js",
    "dev": "nodemon app.js",`
